version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - aws s3 sync --delete ./site "s3://awswellarchitectedlabs-static" 
 post_build:
   commands:
- echo "post_build step" 
