AWSTemplateFormatVersion: '2010-09-09'
Description: 'Well-Architected Labs on Amplify using Hugo/Learn'

Parameters:
  AmplifyName:
    Description: Name for Amplify deploy
    Type: String
    Default: "WALabs"
  AmplifyDescription:
    Description: Description for Amplify deploy
    Type: String
    Default: "Production WA Labs Branch"
  GitHubAcccesToken:
    Description: Github Access token for repository
    Type: String
  GitHubRepoName:
    Description: Github repository URL
    Type: String
    Default: "https://github.com/awslabs/aws-well-architected-labs"
  HugoVersion:
    Description: Version of Hugo to deploy
    Type: String
    Default: "0.143.1"
  GitHubBranchName:
    Description: Branch to Deploy
    Type: String
    Default: "master"

Resources:
  WALabSite:
    Type: AWS::Amplify::App
    Properties:
      AccessToken: !Ref GitHubAcccesToken
      CustomRules:
        - Source: "/<*>"
          Target: "https://aws.amazon.com/pt/architecture/well-architected/"
          Status: '301'

      EnvironmentVariables:
        -
          Name: "_LIVE_UPDATES"
          Value: !Sub "[{\"name\":\"Hugo\",\"pkg\":\"hugo\",\"type\":\"hugo\",\"version\":\"${HugoVersion}\"}]"
        -
          Name: "_DISABLE_L2_CACHE"
          Value: "true"
      Name: !Ref AmplifyName
      Repository: !Ref GitHubRepoName
      BuildSpec: "version: 0.1\nfrontend:\n  phases:\n    build:\n      commands:\n        - hugo --minify\n  artifacts:\n    baseDirectory: public\n    files:\n      - '**/*'\n  cache:\n    paths: []\n"
      # Tags:
      #   - Tag

  WALabSiteBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt WALabSite.AppId
      BranchName: !Ref GitHubBranchName
      Description: !Ref AmplifyDescription
      EnableAutoBuild: True
      EnablePullRequestPreview: False
      Stage: PRODUCTION
      Tags:
        -
          Key: "displayName"
          Value: !Ref GitHubBranchName
